const BASEZONEPRICE = 8.0;
const ADDZONEPRICE = 4.0;
const BASEZONESTRING = String(BASEZONEPRICE);
const ADDZONESTRING = String(ADDZONEPRICE);
const NETTOBRUTTOFACTOR = 1.2;
export {
  BASEZONEPRICE, ADDZONEPRICE, BASEZONESTRING, ADDZONESTRING, NETTOBRUTTOFACTOR,
};
